using System.ComponentModel.DataAnnotations;

namespace EnrollmentSystem.Web.Models.Entities
{
    public class Student
    {
        [Key]
        public Guid Id { get; set; } // This will be auto-generated by the database.
        public required int StudentId { get; set; } // Manually set by user.

        [MaxLength(25)]
        public required string StudentLastName { get; set; } = string.Empty;

        [MaxLength(25)]
        public string StudentFirstName { get; set; } = string.Empty;

        public string? StudentMiddleName { get; set; } = string.Empty;
        public string StudentCourse { get; set; } = string.Empty;
        public int StudentYear { get; set; }
        public string? StudentRemarks { get; set; } = string.Empty;
        public string? StudentStatus { get; set; } = string.Empty;
    }
}
